//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Patient {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBailorID;
		protected global::System.Web.UI.WebControls.TextBox txtRelationship;
		protected global::System.Web.UI.WebControls.TextBox txtCheckInTime;
		protected global::System.Web.UI.WebControls.TextBox txtOutTime;
		protected global::System.Web.UI.WebControls.TextBox txtEmergencyContact;
		protected global::System.Web.UI.WebControls.TextBox txtECTEL;
		protected global::System.Web.UI.WebControls.TextBox txtBloodType;
		protected global::System.Web.UI.WebControls.TextBox txtHeight;
		protected global::System.Web.UI.WebControls.TextBox txtUID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
