//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Patient {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPID;
	protected global::System.Web.UI.WebControls.Label lblBailorID;
	protected global::System.Web.UI.WebControls.Label lblRelationship;
	protected global::System.Web.UI.WebControls.Label lblCheckInTime;
	protected global::System.Web.UI.WebControls.Label lblOutTime;
	protected global::System.Web.UI.WebControls.Label lblEmergencyContact;
	protected global::System.Web.UI.WebControls.Label lblECTEL;
	protected global::System.Web.UI.WebControls.Label lblBloodType;
	protected global::System.Web.UI.WebControls.Label lblHeight;
	protected global::System.Web.UI.WebControls.Label lblUID;


       
    }
}
