//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Equipment {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSN;
		protected global::System.Web.UI.WebControls.TextBox txtEName;
		protected global::System.Web.UI.WebControls.TextBox txtManufactureDate;
		protected global::System.Web.UI.WebControls.TextBox txtValidTime;
		protected global::System.Web.UI.WebControls.TextBox txtSpecification;
		protected global::System.Web.UI.WebControls.TextBox txtModel;
		protected global::System.Web.UI.WebControls.TextBox txtMaintenanceCycle;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtColor;
		protected global::System.Web.UI.WebControls.TextBox txtCount;
		protected global::System.Web.UI.WebControls.TextBox txtTID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
