//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Equipment {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblEID;
	protected global::System.Web.UI.WebControls.Label lblSN;
	protected global::System.Web.UI.WebControls.Label lblEName;
	protected global::System.Web.UI.WebControls.Label lblManufactureDate;
	protected global::System.Web.UI.WebControls.Label lblValidTime;
	protected global::System.Web.UI.WebControls.Label lblSpecification;
	protected global::System.Web.UI.WebControls.Label lblModel;
	protected global::System.Web.UI.WebControls.Label lblMaintenanceCycle;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblColor;
	protected global::System.Web.UI.WebControls.Label lblCount;
	protected global::System.Web.UI.WebControls.Label lblTID;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
