//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.PersonalEquipment {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblPEID;
		protected global::System.Web.UI.WebControls.TextBox txtEID;
		protected global::System.Web.UI.WebControls.TextBox txtPID;
		protected global::System.Web.UI.WebControls.TextBox txtEmpID;
		protected global::System.Web.UI.WebControls.TextBox txtGID;
		protected global::System.Web.UI.WebControls.TextBox txtPTime;
		protected global::System.Web.UI.WebControls.TextBox txtNumber;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
