//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.PensnonalDrug {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPDID;
	protected global::System.Web.UI.WebControls.Label lblDTime;
	protected global::System.Web.UI.WebControls.Label lblFrequency;
	protected global::System.Web.UI.WebControls.Label lblDose;
	protected global::System.Web.UI.WebControls.Label lblDID;
	protected global::System.Web.UI.WebControls.Label lblEID;
	protected global::System.Web.UI.WebControls.Label lblPID;
	protected global::System.Web.UI.WebControls.Label lblIMG;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
