//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.PostureHabit {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblPHID;
		protected global::System.Web.UI.WebControls.TextBox txtHeight;
		protected global::System.Web.UI.WebControls.TextBox txtMedicine;
		protected global::System.Web.UI.WebControls.TextBox txtBack;
		protected global::System.Web.UI.WebControls.TextBox txtHead;
		protected global::System.Web.UI.WebControls.TextBox txtWaist;
		protected global::System.Web.UI.WebControls.TextBox txtLeg;
		protected global::System.Web.UI.WebControls.TextBox txtUID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
