//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Service {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblSID;
		protected global::System.Web.UI.WebControls.TextBox txtSName;
		protected global::System.Web.UI.WebControls.TextBox txtStartTime;
		protected global::System.Web.UI.WebControls.TextBox txtEndTime;
		protected global::System.Web.UI.WebControls.TextBox txtFrequency;
		protected global::System.Web.UI.WebControls.TextBox txtMagnitude;
		protected global::System.Web.UI.WebControls.TextBox txtStandard;
		protected global::System.Web.UI.WebControls.TextBox txtSTID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
