//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.AssessRecord {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblAID;
		protected global::System.Web.UI.WebControls.TextBox txtUName;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtFN;
		protected global::System.Web.UI.WebControls.TextBox txtBirthDate;
		protected global::System.Web.UI.WebControls.TextBox txtTheBed;
		protected global::System.Web.UI.WebControls.TextBox txtValuationDate;
		protected global::System.Web.UI.WebControls.TextBox txtEvaluator;
		protected global::System.Web.UI.WebControls.TextBox txtRegistrar;
		protected global::System.Web.UI.WebControls.TextBox txtRecordData;
		protected global::System.Web.UI.WebControls.TextBox txtBADL;
		protected global::System.Web.UI.WebControls.TextBox txtLADL;
		protected global::System.Web.UI.WebControls.TextBox txtLSP;
		protected global::System.Web.UI.WebControls.TextBox txtSysEvaluation;
		protected global::System.Web.UI.WebControls.TextBox txtAssessment;
		protected global::System.Web.UI.WebControls.TextBox txtUID;
		protected global::System.Web.UI.WebControls.TextBox txtComment;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
