//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.AssessRecord {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblAID;
	protected global::System.Web.UI.WebControls.Label lblUName;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblFN;
	protected global::System.Web.UI.WebControls.Label lblBirthDate;
	protected global::System.Web.UI.WebControls.Label lblTheBed;
	protected global::System.Web.UI.WebControls.Label lblValuationDate;
	protected global::System.Web.UI.WebControls.Label lblEvaluator;
	protected global::System.Web.UI.WebControls.Label lblRegistrar;
	protected global::System.Web.UI.WebControls.Label lblRecordData;
	protected global::System.Web.UI.WebControls.Label lblBADL;
	protected global::System.Web.UI.WebControls.Label lblLADL;
	protected global::System.Web.UI.WebControls.Label lblLSP;
	protected global::System.Web.UI.WebControls.Label lblSysEvaluation;
	protected global::System.Web.UI.WebControls.Label lblAssessment;
	protected global::System.Web.UI.WebControls.Label lblUID;
	protected global::System.Web.UI.WebControls.Label lblComment;


       
    }
}
