//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Drug {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblDID;
		protected global::System.Web.UI.WebControls.TextBox txtDrugName;
		protected global::System.Web.UI.WebControls.TextBox txtDlevel;
		protected global::System.Web.UI.WebControls.TextBox txtManufactureDate;
		protected global::System.Web.UI.WebControls.TextBox txtValidTime;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtSpecification;
		protected global::System.Web.UI.WebControls.TextBox txtDrugSource;
		protected global::System.Web.UI.WebControls.TextBox txtInDate;
		protected global::System.Web.UI.WebControls.TextBox txtStoragetempera;
		protected global::System.Web.UI.WebControls.TextBox txtManufacturers;
		protected global::System.Web.UI.WebControls.TextBox txtBrand;
		protected global::System.Web.UI.WebControls.TextBox txtDrugIMG;
		protected global::System.Web.UI.WebControls.TextBox txtTID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
