//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF_Server.Web.Drug {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblDID;
	protected global::System.Web.UI.WebControls.Label lblDrugName;
	protected global::System.Web.UI.WebControls.Label lblDlevel;
	protected global::System.Web.UI.WebControls.Label lblManufactureDate;
	protected global::System.Web.UI.WebControls.Label lblValidTime;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblSpecification;
	protected global::System.Web.UI.WebControls.Label lblDrugSource;
	protected global::System.Web.UI.WebControls.Label lblInDate;
	protected global::System.Web.UI.WebControls.Label lblStoragetempera;
	protected global::System.Web.UI.WebControls.Label lblManufacturers;
	protected global::System.Web.UI.WebControls.Label lblBrand;
	protected global::System.Web.UI.WebControls.Label lblDrugIMG;
	protected global::System.Web.UI.WebControls.Label lblTID;


       
    }
}
